package day07

import (
	"reflect"
	"testing"
)

func TestParse(t *testing.T) {
	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

	splitters, origin, rows := parse(input)

	want := map[point]struct{}{
		{2, 7}: {},
		{4, 6}: {}, {4, 8}: {},
		{6, 5}: {}, {6, 7}: {}, {6, 9}: {},
		{8, 4}: {}, {8, 6}: {}, {8, 10}: {},
		{10, 3}: {}, {10, 5}: {}, {10, 9}: {}, {10, 11}: {},
		{12, 2}: {}, {12, 6}: {}, {12, 12}: {},
		{14, 1}: {}, {14, 3}: {}, {14, 5}: {}, {14, 7}: {}, {14, 9}: {}, {14, 13}: {},
	}

	if !reflect.DeepEqual(want, splitters) {
		t.Errorf("got %v wanted %v", splitters, want)
	}

	wantOrigin := 7
	if origin != wantOrigin {
		t.Errorf("expected origin at %d, got %d", wantOrigin, origin)
	}
	wantRows := 16
	if rows != wantRows {
		t.Errorf("expected %d rows, got %d", wantRows, rows)
	}
}

func TestPart1(t *testing.T) {
	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	want := "21"
	got, err := Day07{}.Part1(input)
	if err != nil {
		t.Errorf("part 1 returned error - %s", err.Error())
	}

	if got != want {
		t.Errorf("got %s want %s", got, want)
	}
}

func TestPart2(t *testing.T) {
	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	want := "40"
	got, err := Day07{}.Part2(input)
	if err != nil {
		t.Errorf("part 2 returned error - %s", err.Error())
	}

	if got != want {
		t.Errorf("got %s want %s", got, want)
	}
}
